### ISSUE TITLE
Files built will misinform the version implemented

### ISSUE THREAD

**Issue by pietraferreira** [pietraferreira/corev-gcc#3]
Files built with this compiler will misinform the implemented version of the Zc* extension.

```
Attribute Section: riscv
File Attributes
  Tag_RISCV_stack_align: 16-bytes
  Tag_RISCV_arch: "rv32i2p1_zca0p7_zcb0p7_zcmb0p7"
```

To reproduce: empty C file with `-march=rv32izcmb`, compiled with `-S`

Version should be `v0.70.4`

**Comment by CharKeaney** [comment]
Making this change would require changing how versions are handled internally (as at present only major and minor version numbers may be stored) so we should carefully consider this change beforehand. However, changing 0p7 to 0p70 would be trivial.
